#!/usr/bin/env node
/**
 * HOUSE VOICE, DERIVED FROM THE PAGE ITSELF.
 *
 * The AI writer must not learn "PGP Bharat facts" — it must learn HOW this
 * institution writes, so it can draft for any programme page. So this reads the
 * published copy and measures the shape of it: how long a heading runs, how a
 * statistic is punctuated, which dash is used, whether sentences end in a full
 * stop. Facts stay out; form comes through.
 *
 *   node scripts/extract-voice.mjs [slug]
 */
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";

const ROOT = path.resolve(import.meta.dirname, "..");
const slug = process.argv[2] || "pgp-bharat";
const db = new DatabaseSync(path.join(ROOT, "data/content.db"));

const rows = db.prepare(
  "SELECT field_key, tag, value, section_title, tab_title FROM page_content WHERE page_slug = ? ORDER BY section_ord, ord"
).all(slug);
if (!rows.length) {
  console.error("No content for slug " + slug);
  process.exit(1);
}

const vals = rows.map((r) => r.value);
const uniq = [...new Set(vals)];

/* ---------- measurable habits ---------- */
const pct = (n) => Math.round((n / uniq.length) * 100);
const count = (re) => uniq.filter((v) => re.test(v)).length;

const lenByTag = {};
for (const r of rows) {
  (lenByTag[r.tag] ||= []).push(r.value.length);
}
const stats = (a) => {
  const s = [...a].sort((x, y) => x - y);
  return { n: s.length, med: s[Math.floor(s.length / 2)], p90: s[Math.floor(s.length * 0.9)], max: s[s.length - 1] };
};

/* ---------- representative examples, longest first ---------- */
const sample = (pred, n, minLen = 0) =>
  uniq.filter((v) => v.length >= minLen && pred(v))
      .sort((a, b) => b.length - a.length)
      .slice(0, n);

const body      = sample((v) => /[.!?]$/.test(v) && v.length > 90, 8);
const fragments = sample((v) => !/[.!?]$/.test(v) && v.length > 45, 8);
const statLines = sample((v) => /^[₹$]?[\d,]+\+?\s*\S/.test(v) && v.length < 40, 12);
const eyebrows  = sample((v) => v === v.toUpperCase() && /[A-Z]{4}/.test(v) && v.length < 45, 8);
const ctas      = [...new Set(rows.filter((r) => r.tag === "button" || r.tag === "a").map((r) => r.value))].slice(0, 10);

const prose     = uniq.filter((v) => v.length > 60);
const cnt       = (a, re) => a.filter((v) => re.test(v)).length;
const share     = (n, d) => (d ? Math.round((n / d) * 100) : 0);

const emDashN   = cnt(prose, /—/);
const enDashEx  = uniq.filter((v) => /\d\s*–\s*\d/.test(v));
const curly     = count(/[’‘“”]/);
const straight  = count(/['"]/);
const bang      = count(/!/);
const plusStat  = count(/\d\+/);
const oxfordN   = cnt(prose, /,\s*(and|or)\s/);
const brit      = count(/programme/i);
const amer      = count(/program(?!me)/i);

const md = `# House voice — ${slug}

Generated by \`scripts/extract-voice.mjs\` from ${rows.length} published fields.
Regenerate for any page: \`node scripts/extract-voice.mjs <slug>\`.

**Read this as rules of FORM, not a source of facts.** Nothing here describes
what a programme contains — only how this institution puts words together. Never
carry a place name, number, or claim out of the examples below into new copy.

---

## 1. Length is the hardest constraint

Copy is written to a slot. Exceeding the slot breaks the layout, so length is a
rule, not a preference.

| Element | Fields | Median | 90th pct | Never exceed |
|---|---|---|---|---|
${Object.entries(lenByTag)
  .filter(([, a]) => a.length >= 3)
  .sort((a, b) => b[1].length - a[1].length)
  .slice(0, 9)
  .map(([tag, a]) => {
    const s = stats(a);
    return `| \`${tag}\` | ${s.n} | ${s.med} chars | ${s.p90} | ${s.max} |`;
  }).join("\n")}

Headings are **short** — a median heading is a handful of words. If a rewrite
runs past the 90th percentile for its element, it is wrong regardless of how
well it reads.

## 2. Punctuation habits

*Measured over the ${prose.length} fields longer than 60 characters — the ones
that actually contain prose. Percentages over all ${uniq.length} fields would be
swamped by one- and two-word labels.*

- **Em dash (—) for the pivot** — ${emDashN} of ${prose.length} prose fields
  (${share(emDashN, prose.length)}%). It is the house move for a mid-sentence
  turn, where another writer would start a new sentence. Use it; don't force it.
- **No exclamation marks.** ${bang} in the entire corpus. This one is absolute —
  enthusiasm is carried by the verb.
- **Oxford comma** in ${oxfordN} of ${prose.length} prose fields
  (${share(oxfordN, prose.length)}%). Lean toward using it.
- **"Programme" over "program"** — ${brit} vs ${amer} across the corpus. British
  spelling dominates but is not uniform; prefer *programme* in new copy and
  leave existing fields alone.
${enDashEx.length ? `- **En dash for numeric ranges** — only ${enDashEx.length} example${enDashEx.length === 1 ? "" : "s"} in the corpus (\`${enDashEx[0].match(/\d\s*–\s*\d/)[0]}\`), so treat this as a weak signal rather than a rule.` : ""}

> **Not yet consistent, so normalise going forward:** apostrophes are split
> ${curly} curly to ${straight} straight. Prefer the typographic form (’) in new
> copy, but this is a recommendation from the mixed evidence, not an observed
> house rule.

## 3. Two registers, and they do not mix

**Body copy** ends in a full stop and runs one to two sentences:

${body.map((v) => "> " + v).join("\n>\n")}

**Labels, eyebrows and stats are fragments** — no terminal punctuation:

${fragments.map((v) => "- " + v).join("\n")}

Never end a fragment with a full stop. Never let a body sentence run past two
clauses without an em dash doing the work.

## 4. Statistics are terse and pre-rounded

${statLines.map((v) => "- `" + v + "`").join("\n")}

Pattern: **numeral + \`+\` + lowercase noun**. ${plusStat} fields use the
\`N+\` form. The plus does the hedging, so no "approximately", "over", "around",
or "more than". Thousands take a comma only above four digits, and the unit stays
lowercase unless it is a proper noun.

## 5. Sentence architecture

- **Verb-led imperatives** for anything aspirational: start on the verb, not on
  "You will" or "Our programme offers".
- **Triads.** Three-part lists are the default rhythm — three nouns, three
  clauses, three alliterated tab names. Two feels unfinished, four feels like a
  spec sheet.
- **Audience described as a noun phrase**, opening on the person and closing on
  the intent: *"<person type>, <qualifier>, <qualifier> seeking <outcome>."*
- **Concrete over abstract.** Where a list is possible, enumerate the actual
  items rather than summarising them as "everything you need".
- **No second-person sales voice.** No "Don't miss out", "Join us today",
  "Unlock your potential", "in today's fast-paced world".

${eyebrows.length ? `## 6. Eyebrows and section kickers

Set in capitals, no terminal punctuation, ${Math.max(...eyebrows.map((e) => e.length))} characters at the outside:

${eyebrows.map((v) => "- " + v).join("\n")}
` : ""}
## ${eyebrows.length ? "7" : "6"}. Calls to action

${ctas.map((v) => "- " + v).join("\n")}

One or two words. Verb first. No terminal punctuation, no "Click here", no
"Learn more →" with decoration.

## ${eyebrows.length ? "8" : "7"}. Words this house uses deliberately

- **Bharat vs India** — both appear and they are not interchangeable. Never swap
  one for the other in a rewrite; keep whichever the field already used.
- **Immersion, cohort, hub, programme** are the house nouns.
- **"Programme" is the dominant spelling** (see §2) — prefer it, but do not
  "correct" an existing field that uses the other form.

---

## Rules for the assistant

1. Rewrite **one field at a time**, returning only that field's text.
2. Respect the character ceiling for the element. It is a layout constraint.
3. Match the register of the field you were given — fragment stays fragment,
   sentence stays sentence.
4. Never invent a statistic, place, partner, price or date. If the draft needs a
   fact that is not in the current value, leave a \`[TK]\` marker instead.
5. Keep proper nouns, numbers and currency exactly as they are unless the
   instruction is explicitly to change them.
6. Return plain text — no markdown, no quotes around the answer, no preamble.
`;

fs.writeFileSync(path.join(ROOT, "data/voice-guide.md"), md);
console.log("  -> data/voice-guide.md   (" + md.length + " chars, from " + rows.length + " fields)");
